#!/bin/sh

# note: this script assumes that $TLA_HIPL_CACHE is updated periodically

TLA_HIPL_CACHE=~/.tla.get.hipl.cache
REVISION=hipl--main--2.6
TMP_DIR=~/.hipl.howto.tmp.dir
WWW_DIR=/var/www/infrahip/html/hipl/manual
OUTPUT_DIR=$WWW_DIR

set -e

if ! test -d $TMP_DIR
then
  mkdir $TMP_DIR 2>/dev/null
fi

if ! test -d $OUTPUT_DIR
then
  mkdir $OUTPUT_DIR 2>/dev/null
fi

touch $OUTPUT_DIR/DO_NOT_EDIT_THESE_MANUALLY.GENERATED_AUTOMATICALLY
cp -r $TLA_HIPL_CACHE/$REVISION/doc $TMP_DIR
cd $TMP_DIR/doc
#xmlto -o manual html HOWTO.xml 2>/dev/null
#cp -r manual/* $OUTPUT_DIR
make
cp -r howto-html/* $OUTPUT_DIR

