#!/bin/sh -e

umask 022
test -d package || ( echo 'Wrong working directory.'; exit 1 )
test -d src || ( echo 'Wrong working directory.'; exit 1 )

sed -e s}SERVICE}`head -1 compile/conf-service`}g < package/run0 > package/run2
chmod +x package/run2
package/run2
