#!/bin/sh -e

umask 022
test -d package || ( echo 'Wrong working directory.'; exit 1 )
test -d src || ( echo 'Wrong working directory.'; exit 1 )

if test -d SERVICE
then
  echo 'SERVICE exists. I assume that svscan is already running.'
  exit 0
fi

echo 'Creating SERVICE...'
mkdir -p SERVICE

if test -d /etc/event.d
then
  cp package/boot.upstart /etc/event.d/daemontools
  initctl start daemontools
elif test -r /etc/inittab
then
  /usr/sbin/setlock /etc/inittab package/run.inittab
else
  /usr/sbin/setlock /etc/rc.local package/run.rclocal
fi
