#!/bin/sh -e

: ${DESTDIR:=/}
: ${SBINDIR:=usr/sbin}
SBIN="$DESTDIR"/"$SBINDIR"

umask 022
test -d package || ( echo 'Wrong working directory.'; exit 1 )
test -d src || ( echo 'Wrong working directory.'; exit 1 )

here=`env - PATH=$PATH pwd`
parent=`dirname $here`

echo 'Creating symlink daemontools -> daemontools-0.76...'
rm -f daemontools
ln -s daemontools-0.76 daemontools
mv -f daemontools ..

echo "Copying commands to ""$SBIN""..."
mkdir -p "$SBIN"
for i in `cat package/commands`
do
  rm -f "$SBIN"/$i'{new}'
  cp -p $parent/daemontools/command/$i "$SBIN"/$i'{new}'
  chown 0 "$SBIN"/$i'{new}'
  chgrp 0 "$SBIN"/$i'{new}'
  mv -f "$SBIN"/$i'{new}' "$SBIN"/$i
done
