#!/bin/sh

DSTHOST=cochrane
HIPLDIR=~/hipl

seq 1 100 | while read i;do
 tcpdump -w t3dat -n -i eth0 'proto 99' > /dev/null 2>&1 &
 PIDTD=$!
 $HIPLDIR/test/hipsetup -i $DSTHOST >/dev/null 2>&1
 kill $PIDTD
 wait $PIDTD
 I1OUT=$(tcpdump -r t3dat -tt -n | head -1 | cut -f1 -d" ")
 R2IN= $(tcpdump -r t3dat -tt -n | tail -1 | cut -f1 -d" ")
 dt=$(echo "$R2IN-$I1OUT" | bc)
 echo "$i $dt"
done
