#!/bin/sh

# $Id: switchif,v 1.1 2003/10/03 13:13:46 mika Exp $

while true;
do

 echo "waiting for eth1 link to go up"
 while mii-tool eth1 | grep -q "no link"
 do
  sleep .2
 done

 echo "--> eth0 down"
 ifconfig eth0 down
 echo "--> eth1 up"
 ifconfig eth1 up

 echo "waiting for eth0 link to go up"
 while mii-tool eth0 | grep -q "no link"
 do
  sleep .2
 done

 echo "--> eth1 down"
 ifconfig eth1 down
 echo "--> eth0 up"
 ifconfig eth0 up

done
